apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnifleet-billing
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 50056
          livenessProbe:
            grpc:
              port: 50056
          readinessProbe:
            grpc:
              port: 50056
