replicaCount: 2
image:
  repository: ghcr.io/keix40/omnifleet/auth
  tag: latest
jwt:
  issuer: omnifleet
  audience: omnifleet-api
secrets:
  existingSecret: omnifleet-auth-env
pdb:
  minAvailable: 1
