apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnifleet-dispatch
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 50055
          livenessProbe:
            grpc:
              port: 50055
          readinessProbe:
            grpc:
              port: 50055
