replicaCount: 2
image:
  repository: ghcr.io/keix40/omnifleet/gateway
  tag: latest
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
pdb:
  minAvailable: 1
