apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnifleet-notifications
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 50057
          livenessProbe:
            grpc:
              port: 50057
          readinessProbe:
            grpc:
              port: 50057
