apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnifleet-tracking
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
        - name: tracking
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 50052
          livenessProbe:
            grpc:
              port: 50052
          readinessProbe:
            grpc:
              port: 50052
